/**
 * The German terms a player may be asked to picture, in two difficulties.
 *
 * @module
 * @remarks
 * Two hand-picked lists. **Leicht** is mostly concrete, drawable things;
 * **schwer** leans on ideas, places and activities that have no obvious picture
 * ("Langeweile", "Perfektion", "Vergangenheit") and therefore need a detour
 * through something the others can read.
 *
 * Both lists share one convention: entries that are **not** things are written
 * in lower case - activities ("backen", "pilgern") and properties ("giftig",
 * "wortkarg"). That is deliberate and marks them at a glance.
 *
 * A round draws from the list its game was dealt, with the seeded generator, so
 * a game replays identically from its seed and the rules stay testable.
 *
 * The seeding is not what keeps the words secret - the candidate list is public
 * by design, and each player's own term travels in their private hand. What
 * keeps the rest hidden is simply that the base seed never leaves the host.
 *
 * Every entry within a list must be unique: a round deals the terms and the
 * decoys in one draw, and a word listed twice could be dealt twice - handing two
 * players the same term, or making a decoy somebody's real term. The two lists
 * may overlap; only one of them is ever in play. `words.test.ts` guards this.
 */
import { randomInt, type Random } from "./random";
import type { Difficulty } from "./types";

/** The everyday, drawable terms. */
export const EASY_WORDS: readonly string[] = [
  "Surfbrett",
  "Schneeflocke",
  "Wein",
  "Säge",
  "Riesenrad",
  "Hammer",
  "Einkaufswagen",
  "Schreibtisch",
  "Korkenzieher",
  "Skateboard",
  "Textmarker",
  "Dorf",
  "Bär",
  "lesen",
  "Zebra",
  "Raupe",
  "wandern",
  "Ostern",
  "Wasserhahn",
  "Flasche",
  "Pinguin",
  "Kamel",
  "Ernte",
  "Regenwurm",
  "Wahlplakat",
  "Boot",
  "Klavier",
  "Mumie",
  "Leuchtturm",
  "Kopfhörer",
  "Golf",
  "Jagd",
  "Fledermaus",
  "Baumwipfel",
  "Frosch",
  "Terrarium",
  "Badminton",
  "Auge",
  "Tischtennis",
  "Buch",
  "Blume",
  "Tannenbaum",
  "Clown",
  "Flöte",
  "Axt",
  "Palme",
  "Dach",
  "Ratte",
  "Blitzschlag",
  "Harfe",
  "Eule",
  "Obst",
  "Wald",
  "Spaghetti",
  "Trommel",
  "Löwe",
  "Großstadt",
  "Mülleimer",
  "Schornstein",
  "Kastanie",
  "Hängematte",
  "Toaster",
  "Fahrrad",
  "Kaulquappe",
  "Segelboot",
  "Badezimmer",
  "Schaumbad",
  "Kälbchen",
  "Casino",
  "Nudelsieb",
  "Burg",
  "Ski",
  "Tornado",
  "Brille",
  "Planet",
  "Schaukelpferd",
  "Laubhaufen",
  "Hai",
  "Schlagzeug",
  "Mond",
  "Laptop",
  "Augenklappe",
  "Kolibri",
  "Bohrmaschine",
  "Verkehrsschild",
  "Bart",
  "Trauer",
  "Igel",
  "Nachos",
  "Nase",
  "Krankenhaus",
  "Planschbecken",
  "Fußball",
  "Stifte",
  "Ladekabel",
  "Orangensaft",
  "Brot",
  "Eisenbahn",
  "Entfernung",
  "Ampel",
  "Hochzeitstorte",
  "Schatzkarte",
  "tauchen",
  "Zirkus",
  "Erste Hilfe",
  "Schlange",
  "Wolle",
  "Gemüse",
  "Wippe",
  "lachen",
  "Jacke",
  "Getreide",
  "Chilischote",
  "Computer",
  "Rakete",
  "Schere",
  "Sonnenschirm",
  "Vorhänge",
  "Würfelzucker",
  "Apfel",
  "Kirchturmuhr",
  "Koffer",
  "Sonnenblume",
  "Sterne",
  "Käse",
  "Tennis",
  "Feuerwehr",
  "Eisdiele",
  "Zimmerpflanze",
  "Sessellift",
  "Basketball",
  "Radiergummi",
  "Halloween",
  "Blatt",
  "Säule",
  "Tischdecke",
  "Balkon",
  "Weihnachtsbaumkugel",
  "Turm",
  "Lasso",
  "Wäschekorb",
  "Tastatur",
  "spielen",
  "Flamingo",
  "LKW",
  "Mixer",
  "Lavalampe",
  "Eiffelturm",
  "Schatz",
  "Geld",
  "Pasta",
  "Motorrad",
  "Fotografie",
  "Alkohol",
  "Notenschlüssel",
  "Wetter",
  "Taschenmesser",
  "Kajak",
  "Busch",
  "Auto",
  "Vogelscheuche",
  "Zug",
  "Luftballon",
  "Schmetterling",
  "Schrank",
  "Urlaub",
  "Schlamm",
  "Seepferdchen",
  "Wurm",
  "Lesezeichen",
  "Standuhr",
  "Jetski",
  "Postkarte",
  "Strandkorb",
  "Malerei",
  "Seerose",
  "Oase",
  "Krawatte",
  "England",
  "Nordpol",
  "Musik",
  "Papagei",
  "Teppich",
  "Kuhglocke",
  "Heißluftballon",
  "Nachtisch",
  "Himmel",
  "Hubschrauber",
  "Herz",
  "Hund",
  "Babybett",
  "Schwimmbad",
  "Abendkleid",
  "Körper",
  "Deutschland",
  "Statue",
  "Skelett",
  "Waschmaschine",
  "Berggipfel",
  "Winter",
  "Aquarium",
  "Theater",
  "Euter",
  "Geschenk",
  "Teetasse",
  "Laterne",
  "Rucksack",
  "Angel",
  "Schal",
  "Handball",
  "Stempel",
  "Netz",
  "Schlittschuh",
  "Hornisse",
  "Müllhalde",
  "Schokolade",
  "Flugzeug",
  "Strudel",
  "Pizza",
  "Tausendfüßler",
  "rund",
  "Fallschirm",
  "Kran",
  "Geist",
  "Strauß",
  "Wüste",
  "behaart",
  "Gitarre",
  "hüpfen",
  "Wegweiser",
  "Seifenblase",
  "Hampelmann",
  "Kaffee",
  "Fackel",
  "fliegen",
  "Karte",
  "Tür",
  "Essen",
];

/** The harder terms: ideas, places and activities. */
export const HARD_WORDS: readonly string[] = [
  "Lockenwickler",
  "Dudelsack",
  "Mutter",
  "Fortbewegung",
  "genial",
  "Mikroskop",
  "backen",
  "Braten",
  "Afrika",
  "Richterin",
  "Scharnier",
  "Loch Ness",
  "schnell",
  "Weltreise",
  "Leseratte",
  "bügeln",
  "Ferienhaus",
  "Sauerei",
  "irritiert",
  "Wissenschaftlerin",
  "Höhlenmalerei",
  "Traum",
  "Biergarten",
  "Nordlicht",
  "Physik",
  "Japan",
  "Herbst",
  "scharf",
  "Ohrwurm",
  "Chaos",
  "nass",
  "Sofaritze",
  "pilgern",
  "Seuche",
  "Schlaraffenland",
  "Dietrich",
  "Heiligtum",
  "Rollmops",
  "steil",
  "elegant",
  "Wüstenrennmaus",
  "Atlantis",
  "dumm",
  "Tierklinik",
  "Amboss",
  "Ruhm",
  "Kompliment",
  "Muskel",
  "Videospiel",
  "giftig",
  "Rockmusik",
  "Biber",
  "langsam",
  "Witz",
  "Laubbläser",
  "Zoo",
  "graben",
  "Statistik",
  "Küche",
  "Natur",
  "Büro",
  "Pantomime",
  "Nebel",
  "Perfektion",
  "Teleportation",
  "Biologie",
  "Erinnerung",
  "Alpaka",
  "schwimmen",
  "Blattspinat",
  "Rasen mähen",
  "Olympiade",
  "Schredder",
  "Karneval",
  "Trompete",
  "China",
  "Skandinavien",
  "Abneigung",
  "Knäckebrot",
  "Mischung",
  "Zeit",
  "Angst",
  "Pfarrer",
  "entspannt",
  "reiten",
  "Rechnung",
  "glücklich",
  "Naschkatze",
  "Architektin",
  "Schlangenbeschwörer",
  "Kratzbaum",
  "Kaugummi",
  "Schall",
  "zaubern",
  "Napoleon",
  "sitzen",
  "Spiegelbild",
  "Fehler",
  "Tag",
  "Schneewittchen",
  "fahren",
  "Savanne",
  "Australien",
  "Kloster",
  "Expedition",
  "Macht",
  "Posaune",
  "erschrecken",
  "Botschaft",
  "Yoga",
  "Gezeiten",
  "USA",
  "fasten",
  "Europa",
  "Heimweh",
  "Hundeschule",
  "Pirat",
  "Schokoladenbrunnen",
  "servieren",
  "Düsenantrieb",
  "Muttermal",
  "Reichtum",
  "Bauernhof",
  "Langeweile",
  "Zukunft",
  "Blätterteig",
  "Tätowierung",
  "laut",
  "Elster",
  "Fantasie",
  "Restaurant",
  "Umzug",
  "Vortrag",
  "Berlin",
  "Dschungel",
  "schlafen",
  "Polizei",
  "Pilotin",
  "Lasagne",
  "Glaube",
  "Weinhandlung",
  "Universität",
  "Schweißgerät",
  "klebrig",
  "Frieden",
  "sortieren",
  "Absturz",
  "wortkarg",
  "Sänger",
  "Nationalpark",
  "Frühling",
  "Sammlung",
  "Tankstelle",
  "Vergangenheit",
  "Vampir",
  "Delfin",
  "Teufel",
  "Koch",
  "Konzert",
  "Honigwabe",
  "Sportlerin",
  "Weihnachten",
  "Vorfreude",
  "Rattenplage",
  "Lieferung",
  "nachdenken",
  "Dating",
  "Kindergarten",
  "Kneipe",
  "Brettspiel",
  "Grand Canyon",
  "Tauschgeschäft",
  "Maurerin",
  "Batman",
  "schön",
  "hässlich",
  "Bienenstich",
  "Lotterie",
  "Lehrer",
  "Xylophon",
  "klettern",
  "Boxsack",
  "Rathaus",
  "Sommerferien",
  "Taschendiebin",
  "Jenseits",
  "Marke",
  "Auszeichnung",
  "Talisman",
  "Chamäleon",
  "Journalist",
  "Frankreich",
  "Vorgarten",
  "Himalaya",
  "Reflexion",
  "Packesel",
  "bequem",
  "gefährlich",
  "Raumstation",
  "Geburtstagsparty",
  "Südafrika",
  "Mandala",
  "Festival",
  "Waschanlage",
  "Pferdestall",
  "ekelhaft",
  "Tragödie",
  "Paragliderin",
  "Silvester",
  "Geometrie",
  "Künstlerin",
  "Rente",
  "Klettergerüst",
  "Baustelle",
  "wohlklingend",
  "Kannibalin",
  "Baumarkt",
  "Murmelbahn",
  "Konsum",
  "staubsaugen",
  "neidisch",
  "Wickeltisch",
  "Hollywoodschaukel",
  "Paradies",
  "Schmiedin",
  "London",
  "Dinosaurier",
  "Gefängnis",
  "Flohmarkt",
  "Geschichte",
  "Passwort",
  "Hölle",
  "Basar",
  "Demonstration",
  "Bagger",
  "Dichter",
  "Südamerika",
  "Jubiläum",
  "Disco",
];

/** The word pool behind each difficulty. */
const POOLS: Readonly<Record<Difficulty, readonly string[]>> = {
  easy: EASY_WORDS,
  hard: HARD_WORDS,
};

/**
 * The words a difficulty draws from.
 *
 * @param difficulty - the difficulty the game was dealt
 * @returns that difficulty's whole word list
 */
export function wordsFor(difficulty: Difficulty): readonly string[] {
  return POOLS[difficulty];
}

/**
 * Draws a number of distinct terms, avoiding the already used ones.
 *
 * @param random - the seeded generator to draw from
 * @param count - how many terms to deal
 * @param used - the terms already played this game
 * @param difficulty - which list to draw from
 * @returns that many distinct terms
 * @remarks
 * Draws from the still-unused terms; once those run out (a long game) it falls
 * back to the full list, so the round is always dealt in full. The terms within
 * one draw are always distinct - two players never share a word, and a decoy is
 * never also somebody's term.
 */
export function pickWords(
  random: Random,
  count: number,
  used: readonly string[],
  difficulty: Difficulty,
): string[] {
  const pool = wordsFor(difficulty);
  const fresh = pool.filter((word) => !used.includes(word));
  const source = fresh.length >= count ? [...fresh] : [...pool];
  const picked: string[] = [];
  while (picked.length < count && source.length > 0) {
    picked.push(...source.splice(randomInt(random, source.length), 1));
  }
  return picked;
}

/**
 * Shuffles a list with the seeded generator (Fisher-Yates).
 *
 * @param random - the seeded generator to draw from
 * @param words - the words to shuffle
 * @returns a new list in a shuffled order
 * @remarks
 * The candidate list must not betray which words are the real ones, so the
 * terms and the decoys are mixed before anybody sees them.
 */
export function shuffleWords(
  random: Random,
  words: readonly string[],
): string[] {
  const result = [...words];
  for (let i = result.length - 1; i > 0; i--) {
    const j = randomInt(random, i + 1);
    [result[i], result[j]] = [result[j], result[i]];
  }
  return result;
}
